eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: entity-service
          uri: lb://msvc-entity
          predicates:
            - Path=/entities/**
          filters:
            - RewritePath=/entities/(?<path>.*), /$\{path}

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    web: debug
#    root: debug
